name: bloc_rules_plugin
description: A rules for Dart Analyzer that will check some problem cases for flutter_bloc usage
version: 1.0.0
repository: https://github.com/fluttermiddlepodcast/bloc_rules_plugin

environment:
  sdk: ">= 3.9.0"

dependencies:
  analyzer_plugin: ^0.13.7
  analyzer: ^8.1.1
  analysis_server_plugin: ^0.3.3

dev_dependencies:
  lints: ^5.0.0
