name: bloc_example
description: Example project with core BLoC concepts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  yx_state: ^1.0.0
  yx_state_flutter: ^1.0.0

  yx_scope: ^1.0.0
  yx_scope_flutter: ^1.0.0

  dio: ^5.4.0
  path_provider: ^2.1.5
  freezed_annotation:
  json_annotation: ^4.8.1
  shimmer: ^3.0.0

  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed:
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
